#include<msp430.h>
BUZ1 EQU BIT3
BUZ2 EQU BIT4
RSEG CSTACK
Reset:
MOV.W #SFE(CSTACK),SP
main:
MOV.W #WDTPW|WDTHOLD,&WDTCTL
MOV.B #BUZ2,&P2OUT
BIS.B #BUZ1|BUZ2,&P2DIR
MOV.W #500,&TACCR0
MOV.W #CCIE,&TACCTL0
MOV.W #MC_1|ID_3|TASSEL_2|TACLR,&TACTL
BIS.W #GIE,SR
JMP $

TA0_ISR
XOR.B #BUZ1||~BUZ1,&P2OUT

COMMON INTVEC
ORG TIMERA0_VECTOR
DW TA0_ISR
ORG RESET_VECTOR
DW RESET
END
